# codemagic.yaml

# Define the workflow
workflows:
  version: 2

  # Build configuration for iOS
  ios:
    # Specify the workflow name
    name: Build and Deploy iOS

    # Trigger the workflow on each push to the main branch
    script:
      - name: Build
        script: |
          # Install dependencies and build the app
          npm install
          ionic build --prod

          # Move the necessary files to the iOS build directory
          cp -R platforms/ios/* $CM_BUILD_DIR/ios

      - name: Archive
        script: |
          # Archive the iOS project
          cd $CM_BUILD_DIR/ios
          xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -configuration Release -archivePath YourApp.xcarchive archive

      - name: Export
        script: |
          # Export the archive to an IPA file
          xcodebuild -exportArchive -archivePath YourApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR/ios

    artifacts:
      # Specify the path to the IPA file
      - build/ios/*.ipa

# You can define additional workflows for Android, testing, etc.
# ...

# Environment variables that can be used in the script
environment:
  vars:
    - CM_BUILD_DIR: "$HOME/codemagic-build"

# Define global configuration options
# ...
